[package]
name = "stm32_timer_calculator"
version = "0.1.0"
authors = ["Dylan Wishner <dylanwishner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"